/** This file was automatically generated by netlify-cms-toolkit **/
/** Any changes will be overwritten, do not edit it!             **/
import load from "../src/__tests__/fixtures/dummy-loader";

export const contents = [
  {
    collection: `guide_tags`,
    location: `guide_tags/animals.en.md`,
    slug: `animals`,
    locale: `en`,
    raw: null,
    data: {
      title: `Animals`,
    } as const,
    Component: load(import(`./guide_tags/animals.en.md`)),
  } as const,
  {
    collection: `guide_tags`,
    location: `guide_tags/animals.fr.md`,
    slug: `animals`,
    locale: `fr`,
    raw: null,
    data: {
      title: `Animaux`,
    } as const,
    Component: load(import(`./guide_tags/animals.fr.md`)),
  } as const,
  {
    collection: `guide_tags`,
    location: `guide_tags/animals.pt.md`,
    slug: `animals`,
    locale: `pt`,
    raw: null,
    data: {
      title: `Animais`,
    } as const,
    Component: load(import(`./guide_tags/animals.pt.md`)),
  } as const,
  {
    collection: `guide_tags`,
    location: `guide_tags/plants.en.md`,
    slug: `plants`,
    locale: `en`,
    raw: null,
    data: {
      title: `Plants`,
    } as const,
    Component: load(import(`./guide_tags/plants.en.md`)),
  } as const,
  {
    collection: `guide_tags`,
    location: `guide_tags/plants.fr.md`,
    slug: `plants`,
    locale: `fr`,
    raw: null,
    data: {
      title: `Plantes`,
    } as const,
    Component: load(import(`./guide_tags/plants.fr.md`)),
  } as const,
  {
    collection: `guide_tags`,
    location: `guide_tags/plants.pt.md`,
    slug: `plants`,
    locale: `pt`,
    raw: null,
    data: {
      title: `Plantas`,
    } as const,
    Component: load(import(`./guide_tags/plants.pt.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-animals-and-plants.en.md`,
    slug: `about-animals-and-plants`,
    locale: `en`,
    raw: null,
    data: {
      title: `About animals and plants`,
      guide_tags: [`animals`, `plants`],
    } as const,
    Component: load(import(`./guides/about-animals-and-plants.en.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-animals.en.md`,
    slug: `about-animals`,
    locale: `en`,
    raw: null,
    data: {
      title: `About animals`,
      guide_tags: [`animals`],
    } as const,
    Component: load(import(`./guides/about-animals.en.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-animals.fr.md`,
    slug: `about-animals`,
    locale: `fr`,
    raw: null,
    data: {
      title: `\u00C0 propos d'animaux`,
      guide_tags: [`animals`],
    } as const,
    Component: load(import(`./guides/about-animals.fr.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-animals.pt.md`,
    slug: `about-animals`,
    locale: `pt`,
    raw: null,
    data: {
      title: `Sobre animais`,
      guide_tags: [`animals`],
    } as const,
    Component: load(import(`./guides/about-animals.pt.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-plants.en.md`,
    slug: `about-plants`,
    locale: `en`,
    raw: null,
    data: {
      title: `About plants`,
      guide_tags: [`plants`],
    } as const,
    Component: load(import(`./guides/about-plants.en.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-plants.fr.md`,
    slug: `about-plants`,
    locale: `fr`,
    raw: null,
    data: {
      title: `\u00C0 propos des plantes`,
      guide_tags: [`plants`],
    } as const,
    Component: load(import(`./guides/about-plants.fr.md`)),
  } as const,
  {
    collection: `guides`,
    location: `guides/about-plants.pt.md`,
    slug: `about-plants`,
    locale: `pt`,
    raw: null,
    data: {
      title: `Sobre plantas`,
      guide_tags: [`plants`],
    } as const,
    Component: load(import(`./guides/about-plants.pt.md`)),
  } as const,
] as const;

export type Content = typeof contents[number];
