/** This file was automatically generated by netlify-cms-toolkit **/
/** Any changes will be overwritten, do not edit it!             **/
import load from "../../../../src/__tests__/fixtures/dummy-loader";

export const contents = [
  {
    collection: `multiple_files_folder_collection`,
    location: `content/multiple_files_folder_collection/multiple-files-folder-collection-item-1.en.md`,
    slug: `multiple-files-folder-collection-item-1`,
    locale: `en`,
    raw: `---\ntitle: Multiple Files Folder Collection Item 1\n---\nMultiple Files Folder Collection Item 1 (en)`,
    data: {
      title: `Multiple Files Folder Collection Item 1`,
    } as const,
    Component: load(
      import(
        `./content/multiple_files_folder_collection/multiple-files-folder-collection-item-1.en.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_files_folder_collection`,
    location: `content/multiple_files_folder_collection/multiple-files-folder-collection-item-1.fr.md`,
    slug: `multiple-files-folder-collection-item-1`,
    locale: `fr`,
    raw: `---\ntitle: Multiple Files Folder Collection Item 1 (fr)\n---\nMultiple Files Folder Collection Item 1 (fr)`,
    data: {
      title: `Multiple Files Folder Collection Item 1 (fr)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_files_folder_collection/multiple-files-folder-collection-item-1.fr.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_files_folder_collection`,
    location: `content/multiple_files_folder_collection/multiple-files-folder-collection-item-1.pt.md`,
    slug: `multiple-files-folder-collection-item-1`,
    locale: `pt`,
    raw: `---\ntitle: Multiple Files Folder Collection Item 1 (pt)\n---\nMultiple Files Folder Collection Item 1 (pt)`,
    data: {
      title: `Multiple Files Folder Collection Item 1 (pt)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_files_folder_collection/multiple-files-folder-collection-item-1.pt.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_files_folder_collection`,
    location: `content/multiple_files_folder_collection/multiple-files-folder-collection-item-2.en.md`,
    slug: `multiple-files-folder-collection-item-2`,
    locale: `en`,
    raw: `---\ntitle: Multiple Files Folder Collection Item 2\n---\nMultiple Files Folder Collection Item 2 (en)`,
    data: {
      title: `Multiple Files Folder Collection Item 2`,
    } as const,
    Component: load(
      import(
        `./content/multiple_files_folder_collection/multiple-files-folder-collection-item-2.en.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_files_folder_collection`,
    location: `content/multiple_files_folder_collection/multiple-files-folder-collection-item-2.fr.md`,
    slug: `multiple-files-folder-collection-item-2`,
    locale: `fr`,
    raw: `---\ntitle: Multiple Files Folder Collection Item 2 (fr)\n---\nMultiple Files Folder Collection Item 2 (fr)`,
    data: {
      title: `Multiple Files Folder Collection Item 2 (fr)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_files_folder_collection/multiple-files-folder-collection-item-2.fr.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_files_folder_collection`,
    location: `content/multiple_files_folder_collection/multiple-files-folder-collection-item-2.pt.md`,
    slug: `multiple-files-folder-collection-item-2`,
    locale: `pt`,
    raw: `---\ntitle: Multiple Files Folder Collection Item 2 (pt)\n---\nMultiple Files Folder Collection Item 2 (pt)`,
    data: {
      title: `Multiple Files Folder Collection Item 2 (pt)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_files_folder_collection/multiple-files-folder-collection-item-2.pt.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_folders_folder_collection`,
    location: `content/multiple_folders_folder_collection/en/multiple-folders-folder-collection-item-1.md`,
    slug: `multiple-folders-folder-collection-item-1`,
    locale: `en`,
    raw: `---\ntitle: Multiple Folders Folder Collection Item 1\n---\nMultiple Folders Folder Collection Item 1 (en)`,
    data: {
      title: `Multiple Folders Folder Collection Item 1`,
    } as const,
    Component: load(
      import(
        `./content/multiple_folders_folder_collection/en/multiple-folders-folder-collection-item-1.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_folders_folder_collection`,
    location: `content/multiple_folders_folder_collection/en/multiple-folders-folder-collection-item-2.md`,
    slug: `multiple-folders-folder-collection-item-2`,
    locale: `en`,
    raw: `---\ntitle: Multiple Folders Folder Collection Item 2\n---\nMultiple Folders Folder Collection Item 2 (en)`,
    data: {
      title: `Multiple Folders Folder Collection Item 2`,
    } as const,
    Component: load(
      import(
        `./content/multiple_folders_folder_collection/en/multiple-folders-folder-collection-item-2.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_folders_folder_collection`,
    location: `content/multiple_folders_folder_collection/fr/multiple-folders-folder-collection-item-1.md`,
    slug: `multiple-folders-folder-collection-item-1`,
    locale: `fr`,
    raw: `---\ntitle: Multiple Folders Folder Collection Item 1 (fr)\n---\nMultiple Folders Folder Collection Item 1 (fr)`,
    data: {
      title: `Multiple Folders Folder Collection Item 1 (fr)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_folders_folder_collection/fr/multiple-folders-folder-collection-item-1.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_folders_folder_collection`,
    location: `content/multiple_folders_folder_collection/fr/multiple-folders-folder-collection-item-2.md`,
    slug: `multiple-folders-folder-collection-item-2`,
    locale: `fr`,
    raw: `---\ntitle: Multiple Folders Folder Collection Item 2 (fr)\n---\nMultiple Folders Folder Collection Item 2 (fr)`,
    data: {
      title: `Multiple Folders Folder Collection Item 2 (fr)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_folders_folder_collection/fr/multiple-folders-folder-collection-item-2.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_folders_folder_collection`,
    location: `content/multiple_folders_folder_collection/pt/multiple-folders-folder-collection-item-1.md`,
    slug: `multiple-folders-folder-collection-item-1`,
    locale: `pt`,
    raw: `---\ntitle: Multiple Folders Folder Collection Item 1 (pt)\n---\nMultiple Folders Folder Collection Item 1 (pt)`,
    data: {
      title: `Multiple Folders Folder Collection Item 1 (pt)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_folders_folder_collection/pt/multiple-folders-folder-collection-item-1.md`
      ),
    ),
  } as const,
  {
    collection: `multiple_folders_folder_collection`,
    location: `content/multiple_folders_folder_collection/pt/multiple-folders-folder-collection-item-2.md`,
    slug: `multiple-folders-folder-collection-item-2`,
    locale: `pt`,
    raw: `---\ntitle: Multiple Folders Folder Collection Item 2 (pt)\n---\nMultiple Folders Folder Collection Item 2 (pt)`,
    data: {
      title: `Multiple Folders Folder Collection Item 2 (pt)`,
    } as const,
    Component: load(
      import(
        `./content/multiple_folders_folder_collection/pt/multiple-folders-folder-collection-item-2.md`
      ),
    ),
  } as const,
  {
    collection: `no_18n_files_collection`,
    location: `content/no_18n_files_collection/about.md`,
    slug: `about`,
    locale: null,
    raw: `---\ntitle: About\n---\nAbout`,
    data: {
      title: `About`,
    } as const,
    Component: load(import(`./content/no_18n_files_collection/about.md`)),
  } as const,
  {
    collection: `no_18n_files_collection`,
    location: `content/no_18n_files_collection/home.md`,
    slug: `home`,
    locale: null,
    raw: `---\ntitle: Home\n---\nHome`,
    data: {
      title: `Home`,
    } as const,
    Component: load(import(`./content/no_18n_files_collection/home.md`)),
  } as const,
  {
    collection: `no_18n_folder_collection`,
    location: `content/no_18n_folder_collection/no-18n-folder-collection-item-1.md`,
    slug: `no-18n-folder-collection-item-1`,
    locale: null,
    raw: `---\ntitle: No 18n Folder Collection Item 1\n---\nNo 18n Folder Collection Item 1`,
    data: {
      title: `No 18n Folder Collection Item 1`,
    } as const,
    Component: load(
      import(
        `./content/no_18n_folder_collection/no-18n-folder-collection-item-1.md`
      ),
    ),
  } as const,
  {
    collection: `no_18n_folder_collection`,
    location: `content/no_18n_folder_collection/no-18n-folder-collection-item-2.md`,
    slug: `no-18n-folder-collection-item-2`,
    locale: null,
    raw: `---\ntitle: No 18n Folder Collection Item 2\n---\nNo 18n Folder Collection Item 2`,
    data: {
      title: `No 18n Folder Collection Item 2`,
    } as const,
    Component: load(
      import(
        `./content/no_18n_folder_collection/no-18n-folder-collection-item-2.md`
      ),
    ),
  } as const,
  {
    collection: `single_file_files_collection`,
    location: `content/single_file_files_collection/about.md`,
    slug: `about`,
    locale: null,
    raw: `---\ntitle: About\n---\nabout`,
    data: {
      title: `About`,
    } as const,
    Component: load(import(`./content/single_file_files_collection/about.md`)),
  } as const,
  {
    collection: `single_file_files_collection`,
    location: `content/single_file_files_collection/home.md`,
    slug: `home`,
    locale: null,
    raw: `---\ntitle: home\n---\nHome`,
    data: {
      title: `home`,
    } as const,
    Component: load(import(`./content/single_file_files_collection/home.md`)),
  } as const,
] as const;

export type Content = typeof contents[number];
